### ISSUE TITLE
whippet deploy doesn't work

### ISSUE THREAD

**Issue by mallorydxw** [dxw/whippet#125]
I presume the version we're using on servers is an old version.

Error message:

```
% /workbench/src/github.com/dxw/whippet/bin/whippet deploy xyz              
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Dxw\Whippet\Dependencies\Installer::__construct(), 2 passed in /workbench/src/github.com/dxw/whippet/src/Modules/Release.php on line 46 and exactly 3 expe
cted in /workbench/src/github.com/dxw/whippet/src/Dependencies/Installer.php:7
Stack trace:                    
#0 /workbench/src/github.com/dxw/whippet/src/Modules/Release.php(46): Dxw\Whippet\Dependencies\Installer->__construct(Object(Dxw\Whippet\Factory), Object(Dxw\Whippet\ProjectDirectory))
#1 /workbench/src/github.com/dxw/whippet/src/Modules/Deploy.php(53): Dxw\Whippet\Modules\Release->create(false)
#2 /workbench/src/github.com/dxw/whippet/src/Whippet.php(45): Dxw\Whippet\Modules\Deploy->deploy(false, 3)
#3 /workbench/src/github.com/dxw/whippet/vendor/dxw/rubbishthorclone/rubbish_thor_clone.class.php(69): Dxw\Whippet\Whippet->deploy('xyz')
#4 /workbench/src/github.com/dxw/whippet/bin/whippet(26): RubbishThorClone->start(Array)
#5 {main}                                   
  thrown in /workbench/src/github.com/dxw/whippet/src/Dependencies/Installer.php on line 7
```

Bisect results:

```
1d1f680967f8e986a5e80f5cd25bcfded343aa67 is the first bad commit
commit 1d1f680967f8e986a5e80f5cd25bcfded343aa67
Author: Duncan Stuart <dgmstuart@gmail.com>
Date:   Wed Nov 30 12:55:07 2016 +0000

    (feature) deps install checks for inspections

    Mocked out the implementation of an InspectionChecker, responsible for
    checking to see if there are inspections associated with a plugin.

    - Somewhat hairy mocking: we need to pass a function which returns the
      correct results corresponding to each combination of inputs. A lookup
      associative array seems like the easiest way of doing that, but isn't
      very easy to read.
    - Refactored the main spec to pull out the individual lockfile entries
      so that they can be used in the stubbing
    - N.B. There isn't any test coverage of the top-level injections of
      InspectionChecker into the Installer instances

:040000 040000 6844b6301671881b0e355d02980f18304904ad26 643235bc8b5bb4ffd24b54e4937d079c6e1300d2 M      src
:040000 040000 649ee5c83f4aa1d28d77b542c6e6e15e57772eaa c4cd625afe79dc0481774841ba4ab859fa043b03 M      tests
```

**Comment by RobjS** [comment]
This was resolved in https://github.com/dxw/whippet/commit/9059d2899987ba1b8ad569c63d42b1b633719beb#diff-cd6f8e21f20c106938beb11d40dd772822a77d3a65f678b49e3d4d5c115f8e73.
